#!/bin/bash

firefox -new-tab -url https://github.com/jarun/nnn/wiki/Usage-new-tab -url https://www.tecmint.com/linux-directory-structure-and-important-files-paths-explained/ -new-tab -url https://ratfactor.com/dwm -new-tab -url /usr/share/vim/graphical.png
