#!/bin/bash

cp /home/$USER/.xinitrc /home/$USER/scripts/confSync/xinitrc
#basic vim settings kept in /etc/ for root use
cp /home/$USER/.bashrc /home/$USER/scripts/confSync/bashrc
#cp /home/$USER/.bash_profile /home/$USER/scripts/confSync/bash_profile
cp /home/$USER/.vimrc /home/$USER/scripts/confSync/vimrc
#NNN enviroment variables mostly moved to /etc/enviroment. Only the pretty colors remain
cp /etc/environment /home/$USER/scripts/confSync/environment
#/etc/enviroment is used so that NNN will be configured when using as root
cp /home/$USER/.config/feh/keys /home/$USER/scripts/confSync/keys

#cp /home/$USER/.config/apvlv/apvlvrc /home/$USER/scripts/confSync/apvlvrc
cp /usr/share/applications/vim.desktop /home/$USER/scripts/confSync/vimmy.desktop


