#!/bin/bash
# KEEP IN THE SCRIPTS DIR
# YOU DONT NEED TO PUT IT IN /scripts/dot
cp /home/$USER/.xinitrc /home/$USER/scripts/dot/.xinitrc
cp /home/$USER/.bashrc /home/$USER/scripts/dot/.bashrc
cp /home/$USER/.vimrc /home/$USER/scripts/dot/.vimrc
cp /home/rhom/.config/feh/keys /home/rhom/scripts/dot/keys
cp -R /usr/src/dwm651/ /home/$USER/scripts/dot/
cp -R /usr/src/st/ /home/$USER/scripts/dot/
