#!/bin/bash
# KEEP IN THE SCRIPTS DIR
# YOU DONT NEED TO PUT IT IN /scripts/dot
scri="/home/$USER/scripts/dot"
cp /home/$USER/.config/tmux/tmux.conf $scri/tmux.conf
cp /home/$USER/.xinitrc $scri/.xinitrc
cp /home/$USER/.bashrc $scri/.bashrc
cp /home/$USER/.vimrc $scri/.vimrc
cp /home/$USER/.config/nvim/init.lua $scri/init.lua
cp /etc/lf/lfrc $scri/lfrc
cp /home/$USER/.config/feh/keys $scri/keys
cp /home/$USER/.xremap.yml $scri/.xremap.yml

#DWM
# read -p "Copy Suckless files?"
# cp -R /usr/src/dwm651/ $scri/
# cp -R /usr/src/st/ $scri/
