#!/bin/sh

while true; do
    # POWER=$(curl -s http://192.168.1.75/rpc/Shelly.GetStatus | jq '.["pm1:0"] .apower')
	BATT=$(cat /sys/class/power_supply/BAT0/capacity) 
	DATE=$(date +"%A, M%m %B %d, %Y %I:%M %p") 
    WEATHER=$(weather)
    VIMSWAP=$(ls ~/.local/state/nvim/swap | wc -l)
	#ROOT="$POWER $BATT $DATE" 
	ROOT="Swap:$VIMSWAP | $WEATHER | $BATT% | $DATE" 
	xsetroot -name "$ROOT"
	sleep 5s
done
