#!/bin/bash

DIR="/home/$USER/MEGA/vimwiki"
INPUT=$(echo "$1" | tr '[:upper:]' '[:lower:]')

# Find a file in the directory matching case-insensitively
FILENAME=$(find "$DIR" -maxdepth 1 -type f -iname "${INPUT}.wiki" | head -n 1)

if [ -n "$FILENAME" ]; then
    echo "File '$FILENAME' exists."
    bat "$FILENAME"
else
    echo "File '$DIR/$1.wiki' does not exist (case-insensitive search)."
    exit 1
fi
