#!/bin/bash
if IsChrome; then
  chromium --new-tab " https://mail.google.com/mail/u/0/#inbox"
  chromium --new-tab " https://mail.google.com/mail/u/1/#inbox"
  chromium --new-tab " https://mail.google.com/mail/u/2/#inbox"
  # chromium --new-tab " https://mail.google.com/mail/u/3/#inbox"
else
  chromium --new-window " https://mail.google.com/mail/u/0/#inbox"
  chromium --new-tab " https://mail.google.com/mail/u/1/#inbox"
  chromium --new-tab " https://mail.google.com/mail/u/2/#inbox"
  # chromium --new-tab " https://mail.google.com/mail/u/3/#inbox"
fi
