#!/bin/bash
tmux new-session -s "scratchy"
# if ! tmux has-session -t "scratchy" 2>/dev/null; then
    # st -e tmux new-session -s "scratchy"
# else
    # tmux new-window -b -t "scratchy" 
    # tmux attach-session -t "scratchy"
    # tmux send-keys -t "scratchy" ":e $FILE" Enter
# fi
