#!/bin/bash
# ls /home/$USER/scripts/cheatSheet/ > /home/$USER/scripts/cheatSheet/show.txt
FILENAME="/home/$USER/MEGA/vimwiki/$1.wiki"

if [ -f "$FILENAME" ]; then
    echo "File '$FILENAME' exists."
    
    # Display the file content (optional)
    bat "$FILENAME"

    # Perform other operations (e.g., count lines, words, etc.)
#    echo "File statistics:"
#    echo "Lines: $(wc -l < "$FILENAME")"
#    echo "Words: $(wc -w < "$FILENAME")"
#    echo "Characters: $(wc -c < "$FILENAME")"
else
    echo "File '$FILENAME' does not exist."
    exit 1
fi
