#!/bin/bash

# feh --bg-tile /home/rhom/scripts/screen/bg2.png &

# feh --no-fehbg --bg-center --bg-fill /home/rhom/scripts/screen/planets.jpg /home/rhom/scripts/screen/planets.jpg &
# BATH="/home/rhom/scripts/screen/planets.jpg"
# su rhom
BATH="/home/rhom/scripts/screen/bg2.png"
echo "$BATH"
feh --no-fehbg --bg-center --bg-fill $BATH $BATH
