modmap:
  - name: Global
    application:
      not: steam_proton.steam_proton
    remap:
      CapsLock: Control_L
      LEFTCTRL: Super_L
      Shift_L: Shift_L
      Tab: Tab
    
  - name: Emu
    application:
     only: steam_proton.steam_proton
    remap:
      CapsLock: Shift_L
      LEFTCTRL: Tab
      Shift_L: Control_L
      Tab: CapsLock

keymap:
  # - name: HPdir
  #   application:
  #     only: steam_proton.steam_proton
  #    remap:
  #     "Super_L-h": Left
  #     "Super_L-l": Right
  #     "Super_L-j": Down
  #     "Super_L-k": Up
  - name: Dia
    exact_match: true
    remap:
      "Super_L-w": Up
      "Super_L-s": Down
      "Super_L-a": Left
      "Super_L-d": Right
      "Alt-s": PageDown
      "Alt-w": PageUp
      "Alt-a": "Ctrl-Shift-Tab"
      "Alt-d": "Ctrl-Tab"
  - name: Map 
    exact_match: true
    application:
      only: Chromium
    remap:
      "Control-h": "Ctrl-Shift-Tab"
      "Control-l": "Ctrl-Tab"
      "Control-j": PageDown
      "Control-k": PageUp

