set nocompatible

runtime! plugin/sensible.vim
runtime! archlinux.vim

"set laststatus=1
set laststatus=2
set statusline+="%<%F%m%r" 

call plug#begin()
" List your plugins here
"
Plug 'chrisbra/csv.vim'
Plug 'voldikss/vim-floaterm'
Plug 'tpope/vim-sensible'
Plug 'tpope/vim-surround'
Plug 'junegunn/fzf.vim'
Plug 'junegunn/fzf'
Plug 'chrisbra/Colorizer'
Plug 'vimwiki/vimwiki'
Plug 'chrisbra/Recover.vim'

"Plug 'williamboman/mason.nvim'
"Plug 'williamboman/mason-lspconfig.nvim'
"Plug 'hrsh7th/nvim-cmp'
"Plug 'hrsh7th/cmp-nvim-lsp'
"Plug 'nvim-lua/kickstart.nvim'
call plug#end()

let g:vimwiki_list = [
  \ {'path': '~/MEGA/vimwiki/',
  \ 'syntax': 'default',
  \  'ext': '.wiki',
  \ 'diary_frequency': 'weekly',
  \ 'template_path': '~/MEGA/vimwiki/templates',
    \ 'path_html': '~/MEGA/vimwiki/public_html',
  "\ 'template_default': 'default',
  \ 'template_default': 'def_template',
  \ 'template_ext': '.html'}]

let g:vimwiki_valid_html_tags = 'b,i,s,u,sub,sup,kbd,br,hr, pre, script'

"vvvv for gvim and vim
"function! LF()
"    let temp = tempname()
"    exec 'silent !lf -selection-path=' . shellescape(temp)
"    if !filereadable(temp)
"        redraw!
"        return
"    endif
"    let names = readfile(temp)
"    if empty(names)
"        redraw!
"        return
"    endif
"    exec 'edit ' . fnameescape(names[0])
"    for name in names[1:]
"        exec 'argadd ' . fnameescape(name)
"    endfor
"    redraw!
"endfunction
"command! -bar LF call LF()

filetype plugin indent on

let skip_defaults_vim=1
set clipboard=unnamedplus
filetype on

"nnoremap <leader>fh <cmd>Telescope help_tags<cr>

let @o ='o€ý5xxxk'
let @e ='oprintf("\x1B[€ý5'
"nnoremap <leader>fr <cmd>:RecoverPluginFinish<CR>

" set noswapfile

" Set viewoptions to only save folds and cursor position
set viewoptions=folds,cursor

" Save view automatically when leaving a buffer or writing the file
autocmd BufWinLeave ?* mkview
autocmd BufWritePost ?* mkview

" Load view automatically when entering a buffer
autocmd BufWinEnter ?* silent! loadview


"autocmd BufNewFile,BufReadPost ~/MEGA/vimwiki/* setlocal noswapfile
autocmd BufNewFile,BufReadPost ~/MEGA/vimwiki/* setlocal directory=~/MEGA/.vimwiki/swap//
autocmd BufNewFile,BufReadPost ~/MEGA/vimwiki/* setlocal backupdir=~/MEGA/.vimwiki/bak//

 "map <C-t> :tabnew<CR>
 "map <C-w> :tabclose<CR>
"nnoremap <C-S-I> :tabprevious<CR>
"nnoremap <C-I> :tabnext<CR>
"Maps next and previos tab
"map <PageDown> <C-d>
"map <PageUp> <C-u>


" Find files using Telescope command-line sugar.
nnoremap <leader>ff <cmd>Files<cr>
nnoremap <leader>fb <cmd>Buffers<cr>
nnoremap <leader>tt <C-w>T
"nnoremap <leader>fh <cmd>Helptags<cr>
nnoremap <leader>qq <cmd>:q<cr>
nnoremap <leader>QQ <cmd>:q!<cr>
nnoremap <leader>wq <cmd>:wq<cr>
nnoremap <leader>WQ <cmd>:wq!<cr>

nnoremap ? :nohlsearch<CR>

function! LeftRecover()
    wincmd l
    diffget
    RecoverPluginFinish
    write
endfunction

function! RightRecover()
    wincmd l
    diffput
    RecoverPluginFinish
    write
endfunction

command Fin :RecoverPluginFinish
command Left call LeftRecover()
command Right call RightRecover()
command Rec :RecoverPluginHelp
"? clears the search field
inoremap <C-_> <C-p>
" Ctrl-/ behaves like Ctrl-P
inoremap <C-p> <Esc>
" Ctrl-P behaves like Escape
nnoremap <C-_> <C-p>
 nnoremap gf gT
 nnoremap gh gt
nnoremap gT :tabnew<CR>
"nnoremap 

" Make Ctrl-/ act like Ctrl-P (previous command)
"nnoremap <C-p> <Nop>
" makes ctrl-p do nothing in command mode

set backup                 " enable backup files
set writebackup            " keep a backup while writing
set backupdir=~/.local/share/nvim/backup
set backupext=.bak         " use .bak extension
set laststatus=1
set undofile
" set undodir=~/.vim/undodir " Or your preferred directory for undo files
set undodir=~/.local/share/nvim/undo
set relativenumber
set number
set showmode
set shiftwidth=4
set tabstop=4
set expandtab
set showmatch
set hlsearch
colo slate
set cursorline
set ignorecase
set cursorcolumn
set wrap
set scrolloff=10
set wildignore=*.docx,*.jpg,*.png,*.gif,*.pdf,*.pyc,*.exe,*.flv,*.img,*.xlsx
set title
set titlestring=%F
