#!/bin/sh

prefix="/usr"
exec_prefix="${prefix}"
xrdb="xrdb"
xinitdir="/etc/X11/xinit"
xclock="xclock"
xterm="st"
twm="dwm"
xmodmap="xmodmap"

userresources="$HOME/.Xresources"
usermodmap="$HOME/.Xmodmap"
sysresources="$xinitdir/.Xresources"
sysmodmap="$xinitdir/.Xmodmap"

# merge in defaults and keymaps

if [ -f "$sysresources" ]; then
    if [ -x /usr/bin/cpp ] ; then
        "$xrdb" -merge "$sysresources"
    else
        "$xrdb" -nocpp -merge "$sysresources"
    fi
fi

if [ -f "$sysmodmap" ]; then
    "$xmodmap" "$sysmodmap"
fi

if [ -f "$userresources" ]; then
    if [ -x /usr/bin/cpp ] ; then
        "$xrdb" -merge "$userresources"
    else
        "$xrdb" -nocpp -merge "$userresources"
    fi
fi

if [ -f "$usermodmap" ]; then
    "$xmodmap" "$usermodmap"
fi

# start some nice programs

if [ -d "$xinitdir"/xinitrc.d ] ; then
	for f in "$xinitdir/xinitrc.d"/?*.sh ; do
		[ -x "$f" ] && . "$f"
	done
	unset f
fi

# ./.screenlayout/default.sh &
# ./.default.sh &
./scripts/screen/hd $
# feh --bg-fill /home/$USER/.config/bg3.jpg &
./scripts/dwmbar &
./scripts/screen/brutepaper &
./etc/X11/xinit/xinitrc.d/50-systemd-user.sh &
# ./.fehbg &
# setxkbmap -option 'caps:ctrl_modifier' &
# xremap --watch /home/$USER/.xremap.yml &
xremap --watch ~/scripts/dot/xremap.yml &
echo 0 | sudo tee /sys/module/snd_hda_intel/parameters/power_save &
clipmenud &
numlockx &
megasync &
nm-applet &
mullvad-vpn &
# feh --bg-scale ~/.config/bg3.jpg &
"$twm" 
#"$xclock" -geometry 50x50-1+1 &
#"$xterm" -geometry 80x50+494+51 &
#"$xterm" -geometry 80x20+494-0 &
#exec "$xterm" -geometry 80x66+0+0 -name login
#exec dwm

