#!/bin/bash
if IsChrome; then
  chromium --new-tab " https://www.youtube.com/results?search_query=heavy+electronic"
else
  chromium --new-window " https://www.youtube.com/results?search_query=heavy+electronic"
fi
